//
//  NoteDetailsPresenterTests.swift
//  NoteApp
//
//  Created by asbul on 27.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
/*
@testable import NoteApp
import XCTest

class NoteDetailsPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: NoteDetailsPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupNoteDetailsPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupNoteDetailsPresenter() {
        sut = NoteDetailsPresenter()
    }
    
    // MARK: Test doubles
    
    class NoteDetailsDisplayLogicSpy: NoteDetailsDisplayLogic {
        var displaySomethingCalled = false
        
        func displaySomething(viewModel: NoteDetails.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething() {
        // Given
        let spy = NoteDetailsDisplayLogicSpy()
        sut.viewController = spy
        let response = NoteDetails.Something.Response()
        
        // When
        sut.presentSomething(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
*/
