//
//  NoteDetailsWorkerTests.swift
//  NoteApp
//
//  Created by asbul on 27.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
/*
@testable import NoteApp
import XCTest

class NoteDetailsWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: NoteDetailsWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupNoteDetailsWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupNoteDetailsWorker() {
        sut = NoteDetailsWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
*/
