//
//  NoteDetailsModels.swift
//  NoteApp
//
//  Created by asbul on 06.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

enum NoteDetails {
    // MARK: Use cases
    enum ShowNoteDetails {
        struct Response {
            let noteHeader: String?
            let noteText: String?
            let noteDate: Date?
        }

        struct ViewModel {
            let noteHeader: String
            let noteText: String
            let noteDate: String
        }
    }

    enum CheckNoteIsEmpty {
        struct Request {
            let noteHeader: String
            let noteText: String
            let noteDate: Date
        }

        struct Response {
            let isEmptyNote: Bool
        }

        struct ViewModel {
            let isEmptyNote: Bool
        }
    }

    enum PassNote {
        struct Request {
            let noteHeader: String
            let noteText: String
            let noteDate: Date
        }
    }
}
