//
//  NoteDetailsWorker.swift
//  NoteApp
//
//  Created by asbul on 06.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol NoteDetailsWorkerProtocol {
    func save(note: Note)
//    func getNotes() -> [Note]
//    func fetchNetworkNotes(completion: @escaping ([NetworkNote]) -> Void)
//    func fetchNoteIconImageData(from urls: [String?], completion: @escaping ([Data?]) -> Void)
}

final class NoteDetailsWorker: NoteDetailsWorkerProtocol {
    func save(note: Note) {
        StorageManager.shared.save(note: note)
    }
}
