//
//  NoteDetailsInteractor.swift
//  NoteApp
//
//  Created by asbul on 06.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NoteDetailsBusinessLogic {
    func provideNoteDetails(request: NoteDetails.ShowNoteDetails.Request)
    func editCreateNote(_ isEditingNote: Bool)
}

protocol NoteDetailsDataStore {
    var note: Note? { get }
    var isEditingNote: Bool { get }
}

class NoteDetailsInteractor: NoteDetailsBusinessLogic, NoteDetailsDataStore {

    var presenter: NoteDetailsPresentationLogic?
    var worker: NoteDetailsWorker?
    var note: Note?
    var isEditingNote: Bool = false

    private func getEditingNoteStatus() -> Bool {
        return (note != nil) ? true : false
    }

    func editCreateNote(_ isEditingNote: Bool) {
        <#code#>
    }
    func provideNoteDetails(request: NoteDetails.ShowNoteDetails.Request) {
        note = request.note
//        worker = NoteDetailsWorker()
//        worker?.formatDate()

        let response = NoteDetails.ShowNoteDetails.Response(
            noteHeader: note?.header,
            noteText: note?.text,
            noteDate: note?.date ?? .now
        )
        presenter?.presentNoteDetails(response: response)
    }
}
