//
//  NoteDetailsPresenter.swift
//  NoteApp
//
//  Created by asbul on 06.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation
protocol NoteDetailsPresentationLogic {
    func presentNoteDetails(response: NoteDetails.ShowNoteDetails.Response)
    func showAlert(response: NoteDetails.CheckNoteIsEmpty.Response)
    func passNote(response: NoteDetails.PassNote.Response)
}

class NoteDetailsPresenter: NoteDetailsPresentationLogic {
//    var worker: NoteDetailsWorker?

    weak var viewController: NoteDetailsDisplayLogic?

    private func formatDate(date: Date?) -> String {
        guard let date = date else { return "" }
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "ru_RU")
        formatter.dateFormat = "dd.MM.YYYY EEEE HH:mm"
        return formatter.string(from: date)
    }

    func presentNoteDetails(response: NoteDetails.ShowNoteDetails.Response) {
//        worker = NoteDetailsWorker()
//        let noteDate = worker?.formatDate(date: response.noteDate)
        let noteDate = formatDate(date: response.noteDate)

        let viewModel = NoteDetails.ShowNoteDetails.ViewModel(
            noteHeader: response.noteHeader ?? "",
            noteText: response.noteText ?? "",
            noteDate: noteDate
        )
        viewController?.displayNoteDetails(viewModel: viewModel)
    }

    func showAlert(response: NoteDetails.CheckNoteIsEmpty.Response) {
        let viewModel = NoteDetails.CheckNoteIsEmpty.ViewModel(isEmptyNote: response.isEmptyNote)
        viewController?.showAlert(viewModel: viewModel)
    }

    func passNote(response: NoteDetails.PassNote.Response) {
        let viewModel = NoteDetails.PassNote.ViewModel(note: response.note)
        viewController?.passNote(viewModel: viewModel)
    }
}
