//
//  NoteListInteractorTests.swift
//  NoteApp
//
//  Created by asbul on 23.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import NoteApp
import XCTest

class NoteListInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: NoteListInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupNoteListInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupNoteListInteractor() {
        sut = NoteListInteractor()
    }
    
    // MARK: Test doubles
    
    class NoteListPresentationLogicSpy: NoteListPresentationLogic {
        var presentSomethingCalled = false
        
        func presentSomething(response: NoteList.Something.Response) {
            presentSomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoSomething() {
        // Given
        let spy = NoteListPresentationLogicSpy()
        sut.presenter = spy
        let request = NoteList.Something.Request()
        
        // When
        sut.doSomething(request: request)
        
        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
