//
//  NoteListWorkerTests.swift
//  NoteApp
//
//  Created by asbul on 23.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
/*
@testable import NoteApp
import XCTest

class NoteListWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: NoteListWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupNoteListWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupNoteListWorker() {
        sut = NoteListWorker()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
*/
