//
//  NoteListPresenterTests.swift
//  NoteApp
//
//  Created by asbul on 23.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
/*
@testable import NoteApp
import XCTest

class NoteListPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: NoteListPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupNoteListPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupNoteListPresenter() {
        sut = NoteListPresenter()
    }
    
    // MARK: Test doubles
    
    class NoteListDisplayLogicSpy: NoteListDisplayLogic {
        var displaySomethingCalled = false
        
        func displaySomething(viewModel: NoteList.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething() {
        // Given
        let spy = NoteListDisplayLogicSpy()
        sut.viewController = spy
        let response = NoteList.Something.Response()
        
        // When
        sut.presentSomething(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
*/
