//
//  NoteListPresenter.swift
//  NoteApp
//
//  Created by asbul on 07.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NoteListPresentationLogic {
    func presentSomething(response: NoteList.Something.Response)
}

class NoteListPresenter: NoteListPresentationLogic {
    
    weak var viewController: NoteListDisplayLogic?
    
    func presentSomething(response: NoteList.Something.Response) {
        let viewModel = NoteList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
