//
//  NoteListModels.swift
//  NoteApp
//
//  Created by asbul on 07.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

// typealias NoteCellViewModel = NoteList.ShowNotes.ViewModel.NoteCellViewModel

enum NoteList {
    // MARK: Use cases
    enum ShowNotes {
        enum Request {
            // i dont know what is that???
//            case getNotes
        }

        struct Response {
            let notes: [Note]
        }

        struct ViewModel {
            var cellViewModels: [CellViewModel]
        }
    }
}
