//
//  NoteListInteractor.swift
//  NoteApp
//
//  Created by asbul on 07.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NoteListBusinessLogic {
    func doSomething(request: NoteList.Something.Request)
}

protocol NoteListDataStore {
    
}

class NoteListInteractor: NoteListBusinessLogic, NoteListDataStore {
    
    var presenter: NoteListPresentationLogic?
    var worker: NoteListWorker?
    
    func doSomething(request: NoteList.Something.Request) {
        worker = NoteListWorker()
        worker?.doSomeWork()
        
        let response = NoteList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
