//
//  NoteListPresenter.swift
//  NoteApp
//
//  Created by asbul on 07.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol NoteListPresentationLogic {
    func presentNotes(response: NoteList.ShowNotes.Response)
}

class NoteListPresenter: NoteListPresentationLogic {
    weak var viewController: NoteListDisplayLogic?

    func presentNotes(response: NoteList.ShowNotes.Response) {
        var cellViewModels: [CellViewModel] = []
        cellViewModels = response.notes.map { CellViewModel(note: $0) }
        let viewModel = NoteList.ShowNotes.ViewModel(cellViewModels: cellViewModels)
        viewController?.displayNotes(viewModel: viewModel)
    }
}
