//
//  NoteListModels.swift
//  NoteApp
//
//  Created by asbul on 07.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

// typealias NoteCellViewModel = NoteList.ShowNotes.ViewModel.NoteCellViewModel

enum NoteList {
    // MARK: Use cases
    enum ShowNotes {
        struct Response {
            let notes: [Note]
        }
        struct ViewModel {
            let cellViewModels: [CellViewModel]
        }
    }

    enum ShowNetworkNotes {
        struct Response {
            let networkNotes: [NetworkNote]
            let networkNoteImages: [Data?]
        }
        struct ViewModel {
            let cellViewModels: [CellViewModel]
        }
    }
//    enum ShowNoteIcons {
//        struct Response {
//            let noteImages: [Data]
//        }
//        struct ViewModel {
//            var cellViewModels: [CellViewModel]
//        }
//    }
}
